### ISSUE TITLE
Incorrect Percentiles reporting

### ISSUE THREAD

**Issue by fuzzycow** [vrischmann/go-metrics-influxdb#1]
Hi,

It looks like when reporting histogram values - all percentiles will be set to same value.

Here's how go-metrics logger fetches the percentiles:
    ps := h.Percentiles([]float64{0.5, 0.75, 0.95, 0.99, 0.999})

Here's influxdb.go:
    "p999":     m.Percentile(99.9),
    "p9999":    m.Percentile(99.99),

From traffic capture. Note the pNN values:

  count=481999i,m1=999.9992707686223,m15=998.8201711297105,m5=999.589420684841,max=1181835i,mean=127654.4280155642,meanrate=999.9936221298891,min=81662i,p50=1181835,p75=1181835,p95=1181835,p99=1181835,p999=1181835,p9999=1181835,stddev=76492.17168321775,variance=5851052328.814858 1445863754555784700

**Comment by vrischmann** [comment]
Hi,

thanks for the bug report. I'll try to take a look at this when I go home from work.

**Comment by fuzzycow** [comment]
Thank you for quick reply!
For now I've manually switched Percentile parameters (e.g.: from 99.99 to 0.9999), and the result looks ok.

**Comment by vrischmann** [comment]
So you we write, that was exactly what was wrong. I should probably find some time for writing some tests.

Anyway, thanks !
