### ISSUE TITLE
influxdb too many file

### ISSUE THREAD

**Issue by lvchengchang** [vrischmann/go-metrics-influxdb#17]
hello,i find if i get server info.after long time.linux show too many ESTABLISHED.

```go
package main

import (
	"time"
	"github.com/rcrowley/go-metrics"
	"github.com/vrischmann/go-metrics-influxdb"
)


func main() {
	r := metrics.NewRegistry()
	metrics.RegisterDebugGCStats(r)
	metrics.RegisterRuntimeMemStats(r)

	go metrics.CaptureDebugGCStats(r, time.Second *5)
	go metrics.CaptureRuntimeMemStats(r, time.Second *5)

	for {
		go influxdb.InfluxDB(
			r,                             // metrics registry
			time.Second * 5,                 // how often
			"***", // InfluxDB url
			"***",                  // InfluxDB database name
			"",                            // InfluxDB user
			"",                            // InfluxDB password
		)
		time.Sleep(time.Second * 3)
	}
}
```

**Comment by lvchengchang** [comment]
netstat -apn | grep 8086 | grep ESTABLISHED | wc -l
(Not all processes could be identified, non-owned process info
 will not be shown, you would have to be root to see it all.)
339

**Comment by vrischmann** [comment]
The code doesn't manage any connection itself, I defer to [client.NewClient](https://github.com/vrischmann/go-metrics-influxdb/blob/master/influxdb.go).

I suggest you write a simple piece of code using only `github.com/influxdata/influxdb1-client` to see if it's reproducible without `go-metrics-influxdb`.

I don't use InfluxDB anymore so I have no experience regarding resource usage.

**Comment by lvchengchang** [comment]
i think nginx have many connection. i ready set nginx timeout time and linux kernel timeout,ready try

**Comment by lvchengchang** [comment]
2019/06/11 17:11:59 unable to send metrics to InfluxDB. err=Post http://×××/write?consistency=&db=×××&precision=&rp=: read tcp ×××:60592->×××:8086: read: connection timed out

**Comment by vrischmann** [comment]
As I've said, I don't use InfluxDB anymore, I can't help you with this.

I'll close this now.
