### ISSUE TITLE
Example Queries/Grafana Dashboard

### ISSUE THREAD

**Issue by andrewwebber** [vrischmann/go-metrics-influxdb#2]
Do you have any example queries or a grafana dashboard that worked for you?

**Comment by vrischmann** [comment]
Hi.

here's a couple of queries I use a lot on my dashboards:

`SELECT sum("m1") FROM "topic.read.meter" WHERE $timeFilter GROUP BY time(1m) fill(0)`

this sum the 1-minute rates for `topic.read.meter`.

`SELECT max("p50") FROM "done.sent.timer" WHERE $timeFilter GROUP BY time(1m) fill(0)`

this gives you the maximum 50-percentile for `done.sent.timer`.

`$timeFilter` is set by grafana. You need to add influx as a data source first.
These are the full queries but really, I just use the default grafana editor to build my metrics from InfluxDB. It's super easy.
