### ISSUE TITLE
inconsistent data type for some metric types

### ISSUE THREAD

**Issue by genturwt** [vrischmann/go-metrics-influxdb#22]
according to https://community.influxdata.com/t/how-to-solve-type-conflicts/8473, one field under the same measurement (regardless of the different buckets) needs to have same field type.

otherwise, we might have errors as shown below
```
2020/01/21 12:28:10 unable to send metrics to InfluxDB. err={"error":"partial write: field type conflict: input field \"process-time.histogram\" on measurement \"item-pipeline\" is type float, already exists as type integer dropped=10"}
````

The fix would be to unify the same data type for each field. For example, for Histogram, we could do the following:
```
fields := map[string]interface{}{
	"count": float64(ms.Count()),
	"m1":    ms.Rate1(),
	"m5":    ms.Rate5(),
	"m15":   ms.Rate15(),
	"mean":  ms.RateMean(),
}
```

Please approve the problem and solution and I can create the MR for it.

**Comment by vrischmann** [comment]
Is this something you experienced recently ? I found [this](https://github.com/influxdata/influxdb-python/issues/572) which seems related and dates back to 2018. I'm wondering if timers/meters and histograms were broken all this time.

Do you maybe have a reproducer program so that I can test myself ?

And if you want to make a PR that would be cool.

**Comment by genturwt** [comment]
yeah, it happened on my services.

I'll try to provide the code to reproduce when I got the time.

**Comment by tehsphinx** [comment]
I have the same issue. Here my test code to reproduce:

```go
package main

import (
	"math/rand"
	"time"

	"github.com/rcrowley/go-metrics"
	influxdb "github.com/vrischmann/go-metrics-influxdb"
)

func main() {
	go influxdb.InfluxDBWithTags(
		metrics.DefaultRegistry, // metrics registry
		time.Second*10,          // interval
		"http://localhost:8086", // the InfluxDB url
		"metrics",               // your InfluxDB database
		"measurement.default",   // your measurement
		"",                      // your InfluxDB user
		"",                      // your InfluxDB password
		map[string]string{},     // your tag set as map[string]string
		false,                   // align the timestamps
	)

	go randomMeter()

	select {}
}

func randomMeter() {
	m := metrics.NewMeter()
	if err := metrics.Register("Test Meter", m); err != nil {
		panic(err)
	}

	for {
		time.Sleep(1000 * time.Millisecond)
		n := rand.Int63n(10)
		m.Mark(n)
	}
}
```
