### ISSUE TITLE
Support for InfluxDB 2.x ?

### ISSUE THREAD

**Issue by jo-me** [vrischmann/go-metrics-influxdb#28]
Hi,
is support for InfluxDB 2.x planned?

Authentication has changed so older clients can't connect anymore.

There is an official influxdb client for 1.8+ and 2.x:
https://github.com/influxdata/influxdb-client-go

Thanks
Jochen

**Comment by vrischmann** [comment]
Hi, 
Sorry, I have no plan to implement support for indluxdb 2 myself as I stopped using influxdb a long time ago.

If someone implements it I'd be happy to review a PR though.
