### ISSUE TITLE
Update to the new influxdb client

### ISSUE THREAD

**Issue by santagada** [vrischmann/go-metrics-influxdb#3]
Thanks for your hard work on this lib. 

I just want to ask if you have plans to support the new v2 client as the old one is deprecated: https://github.com/influxdata/influxdb/tree/master/client

Also the new client supports udp connections, but apparently there is no way to set this up with go-metrics-influxdb.

**Comment by vrischmann** [comment]
Hi,

thanks for the suggestion. I'll look into it, shouldn't be too hard, but I don't know when I'll do it.
