### ISSUE TITLE
Error handling?

### ISSUE THREAD

**Issue by let4be** [vrischmann/go-metrics-influxdb#8]
InfluxDB function should expose errors

**Comment by vrischmann** [comment]
I guess I could expose the errors we might get when creating the client, however given that the reporting is done in the background those errors will never be exposed.

**Comment by let4be** [comment]
The point is to be able to handle errors(reconnect in case of failure) && properly integrate with existing logging system that's in place
ideally there's also should be a way to stop the .run method

**Comment by vrischmann** [comment]
Sorry, I'm not going to do that. This package is essentially feature complete as far as I'm concerned, I'm just keeping it running.

Your use case is totally valid however, so I'd suggest you just fork this project and add the features you want for yourself.
